name: AWS OIDC Test
 
on:
  push:
    branches:
      - main  # Change as needed
 
permissions:
  id-token: write
  contents: read
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Debug OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: 'sts.amazonaws.com'
      
       - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::650687537318:role/GitHubActionsRole
          aws-region: us-east-1  # Change as needed
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Use desired Terraform version
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Plan
        run: terraform plan
 
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
